###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "kami",
    "senha": "2460"
}

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "Rafa",
    "senha": "rlk"
}